// Generated by Selenium IDE
//updated the changes
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class 072prajaktasdmbuyphoneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void 072prajaktasdmbuyphone() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1040, 561));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("fli");
    driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.linkText("Mobile Phones Big Savings ..."));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("motorola");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) .\\_4rR01T")).click();
    vars.put("win13", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win13").toString());
    js.executeScript("window.scrollTo(0,98.68421173095703)");
    driver.findElement(By.cssSelector(".ihZ75k")).click();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.switchTo().window(vars.get("win13").toString());
    vars.put("win7012", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7012").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win7012").toString());
    driver.findElement(By.cssSelector(".ihZ75k")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ihZ75k"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win7012").toString());
    driver.switchTo().window(vars.get("win13").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win13").toString());
    driver.switchTo().window(vars.get("win7012").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).click();
    driver.findElement(By.cssSelector(".LHJvCe")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc > .yuRUbf .LC20lb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(2) .\\_396cs4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(3) .\\_396cs4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(3) .\\_396cs4")).click();
    vars.put("win906", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6205").toString());
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(3) .\\_396cs4"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.switchTo().window(vars.get("win906").toString());
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win906").toString());
    js.executeScript("window.scrollTo(0,7.518796920776367)");
    driver.findElement(By.cssSelector(".ihZ75k")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ihZ75k"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(2) .CXW8mj"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(3) .\\_396cs4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(4) .CXW8mj"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(4) .\\_396cs4")).click();
    vars.put("win5196", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(3) .\\_396cs4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win5196").toString());
    js.executeScript("window.scrollTo(0,125)");
    driver.findElement(By.cssSelector(".ihZ75k")).click();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(2) div:nth-child(2) .\\_2rpwqI > div:nth-child(1) > div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,251.87969970703125)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".\\_1AtVbE:nth-child(3) > .\\_13oc-S > div:nth-child(1) .\\_396cs4")).click();
    vars.put("win5854", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5854").toString());
    driver.findElement(By.cssSelector(".ihZ75k")).click();
  }
}
